services:
  www:
    container_name: www
    build: .
    ports:
      - "8007:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/99-uploads.ini:ro
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  database:
    container_name: database
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mariadb", "--user=root", "--password=root", "-e", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  queue:
    container_name: queue
    image: rabbitmq:3-management    
    ports:
      - 15672:15672
      - 5672:5672
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_listener", "5672"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  smtp:
    container_name: smtp
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8025/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  my-db:
