services:
  www:
    container_name: www
    build: .
    ports:
      - "8007:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  database:
    container_name: database
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  queue:
    container_name: queue
    image: rabbitmq:3-management    
    ports:
      - 15672:15672
      - 5672:5672
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_listener", "amqp"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  my-db:
