name: Label based on PR size

on:
  pull_request:
  workflow_dispatch:
  
jobs:
    label_pr:
        runs-on: ubuntu-latest
        steps:
            - name: Apply size label
              uses: pascalgn/size-label-action@v0.5.4
              with:
                  github_token: ${{ secrets.MY_SECRET }}
                  sizes: '0:SMALL, 10:SMALL, 50:SMALL, 200:MEDIUM, 500:MEDIUM, 1000:LARGE'
